version: '3.8'

services:
  # ==========================================
  # BASES DE DRONES
  # ==========================================
  base_norte:
    build: .
    # Comando: arquivo, ID_Base, Porta, Qtd_Drones
    command: ["go", "run", "drone_base.go", "Base_Norte", "6000", "5"]
    ports:
      - "6000:6000"

  base_sul:
    build: .
    command: ["go", "run", "drone_base.go", "Base_Sul", "6001", "3"]
    ports:
      - "6001:6001"

  # ==========================================
  # GERENCIADORES DE SETOR (BROKERS)
  # ==========================================
  broker_a:
    build: .
    # Comando: arquivo, ID_Broker, Porta_P2P, Porta_Sensor
    command: ["go", "run", "broker.go", "Setor_A", "5001", "7001"]
    environment:
      # Variáveis injetadas para o Broker saber quem são seus vizinhos
      - PEERS=Setor_B|broker_b:5002
      - BASES=base_norte:6000,base_sul:6001
    depends_on:
      - base_norte
      - base_sul

  broker_b:
    build: .
    command: ["go", "run", "broker.go", "Setor_B", "5002", "7002"]
    environment:
      - PEERS=Setor_A|broker_a:5001
      - BASES=base_norte:6000,base_sul:6001
    depends_on:
      - base_norte
      - base_sul

  # ==========================================
  # SENSORES
  # ==========================================
  sensor_a:
    build: .
    # Passando o ID do setor e o endereço do Broker via argumento
    command: ["go", "run", "sensor.go", "Setor_A", "broker_a:7001"]
    depends_on:
      - broker_a

  sensor_b:
    build: .
    command: ["go", "run", "sensor.go", "Setor_B", "broker_b:7002"]
    depends_on:
      - broker_b