services:
  # ==========================================
  # BASES DE DRONES
  # ==========================================
  base_1:
    build: 
      context: ./base
    container_name: base_1
    command: ./base Base_1 6000
    ports:
      - "6000:6000"

  base_2:
    build:
      context: ./base
    container_name: base_2
    command: ./base Base_2 6001
    ports:
      - "6001:6001"

  # ==========================================
  # DRONES (Worker Nodes)
  # ==========================================
  # Drones apontando para a Base 1
  drone_b1:
    build:
      context: ./drone # Você precisará criar o diretório ./drone com o drone.go e um Dockerfile
    command: ./drone ${base_1}:6000 # Argumento apontando para onde ele deve se registrar
    depends_on:
      - base_1 # Garante que o drone só suba depois da base

  drone_b2:
    build:
      context: ./drone
    command: ./drone ${base_2}:6001
    depends_on:
      - base_2

  drone_a1:
    build:
      context: ./drone
    command: ./drone ${base_1}:6000
    depends_on:
      - base_1

  drone_a2:
    build:
      context: ./drone
    command: ./drone ${base_2}:6001
    depends_on:
      - base_2

  # ==========================================
  # BROKERS (GERENCIADORES DE SETOR)
  # ==========================================
  broker_1:
    build:
      context: ./broker
    container_name: broker_1
    command: ./broker Setor_1 5001 7001
    ports:
      - "5001:5001"
      - "7001:7001"
    environment:
      - PEERS=Setor_2|${broker_2}:5002,Setor_3|${broker_3}:5003,Setor_4|${broker_4}:5004,Setor_5|${broker_5}:5005
      - BASES=${base_1}:6000,${base_2}:6001

  broker_2:
    build:
      context: ./broker
    container_name: broker_2
    command: ./broker Setor_2 5002 7002
    ports:
      - "5002:5002"
      - "7002:7002"
    environment:
      - PEERS=Setor_1|${broker_1}:5001,Setor_3|${broker_3}:5003,Setor_4|${broker_4}:5004,Setor_5|${broker_5}:5005
      - BASES=${base_1}:6000,${base_2}:6001

  broker_3:
    build:
      context: ./broker
    container_name: broker_3
    command: ./broker Setor_3 5003 7003
    ports:
      - "5003:5003"
      - "7003:7003"
    environment:
      - PEERS=Setor_1|${broker_1}:5001,Setor_2|${broker_2}:5002,Setor_4|${broker_4}:5004,Setor_5|${broker_5}:5005
      - BASES=${base_1}:6000,${base_2}:6001

  broker_4:
    build:
      context: ./broker
    container_name: broker_4
    command: ./broker Setor_4 5004 7004
    ports:
      - "5004:5004"
      - "7004:7004"
    environment:
      - PEERS=Setor_1|${broker_1}:5001,Setor_2|${broker_2}:5002,Setor_3|${broker_3}:5003,Setor_5|${broker_5}:5005
      - BASES=${base_1}:6000,${base_2}:6001

  broker_5:
    build:
      context: ./broker
    container_name: broker_5
    command: ./broker Setor_5 5005 7005
    ports:
      - "5005:5005"
      - "7005:7005"
    environment:
      - PEERS=Setor_1|${broker_1}:5001,Setor_2|${broker_2}:5002,Setor_3|${broker_3}:5003,Setor_4|${broker_4}:5004
      - BASES=${base_1}:6000,${base_2}:6001   

  # ==========================================
  # SENSORES
  # ==========================================
  sensor_1:
    build:
      context: ./sensores
    container_name: sensor_1
<<<<<<< Updated upstream
    command: ./sensor Setor_1 ${broker_1}:7001
=======
    command: ./sensor Setor_1 ${broker_1}:7001,${broker_5}:7005,${broker_2}:7002
>>>>>>> Stashed changes
      
  sensor_2:
    build:
      context: ./sensores
    container_name: sensor_2
<<<<<<< Updated upstream
    command: ./sensor Setor_2 ${broker_2}:7002
=======
    command: ./sensor Setor_2 ${broker_2}:7002,${broker_1}:7001,${broker_3}:7003
>>>>>>> Stashed changes

  sensor_3:
    build:
      context: ./sensores
    container_name: sensor_3
    command: ./sensor Setor_3 ${broker_3}:7003

  sensor_4:
    build:
      context: ./sensores
    container_name: sensor_4
    command: ./sensor Setor_4 ${broker_4}:7004

  sensor_5:
    build:
      context: ./sensores
    container_name: sensor_5
<<<<<<< Updated upstream
    command: ./sensor Setor_5 ${broker_5}:7005
=======
    command: ./sensor Setor_5 ${broker_5}:7005,${broker_4}:7004,${broker_1}:7001
>>>>>>> Stashed changes
