services:
  # ==========================================
  # BASES DE DRONES
  # ==========================================
  base_norte:
    build: 
      context: ./base # Aponta para a pasta onde está o Dockerfile da base
    container_name: base_norte
    # Executa o binário 'base' com os argumentos: Base_Norte 6000 2
    command: ./base Base_Norte 6000 2
    ports:
      - "6000:6000"

  base_sul:
    build:
      context: ./base
    container_name: base_sul
    command: ./base Base_Sul 6001 2
    ports:
      - "6001:6001"

  # ==========================================
  # BROKERS (GERENCIADORES DE SETOR)
  # ==========================================
  broker_1:
    build:
      context: ./broker # Aponta para a pasta do Broker
    container_name: broker_1
    command: ./broker Setor_1 5001 7001
    environment:
      - PEERS=Setor_2|broker_2:5002
      - BASES=base_norte:6000,base_sul:6001
    depends_on:
      - base_norte
      - base_sul

  broker_2:
    build:
      context: ./broker
    container_name: broker_2
    command: ./broker Setor_2 5002 7002
    environment:
      - PEERS=Setor_1|broker_1:5001
      - BASES=base_norte:6000,base_sul:6001
    depends_on:
      - base_norte
      - base_sul

  # ==========================================
  # SENSORES
  # ==========================================
  sensor_1:
    build:
      context: ./sensores # Aponta para a pasta dos Sensores
    container_name: sensor_1
    command: ./sensor Setor_1 broker_1:7001
    depends_on:
      - broker_1
      
  sensor_2:
    build:
      context: ./sensores # Aponta para a pasta dos Sensores
    container_name: sensor_2
    command: ./sensor Setor_2 broker_2:7002
    depends_on:
      - broker_2